# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: speaker.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rspeaker.proto\"\x19\n\tInputData\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"\x1a\n\nOutputData\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t2+\n\x07Speaker\x12 \n\x05Speak\x12\n.InputData\x1a\x0b.OutputDatab\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'speaker_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INPUTDATA._serialized_start=17
  _INPUTDATA._serialized_end=42
  _OUTPUTDATA._serialized_start=44
  _OUTPUTDATA._serialized_end=70
  _SPEAKER._serialized_start=72
  _SPEAKER._serialized_end=115
# @@protoc_insertion_point(module_scope)
